//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long Id { get; set; }
        public Nullable<long> CreateTime { get; set; }
        public Nullable<long> ModifyTime { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public Nullable<short> IsActive { get; set; }
        public long ProjectId { get; set; }
        public string Title { get; set; }
        public Nullable<long> PostTime { get; set; }
        public string Status { get; set; }
        public string PostType { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public string Tags { get; set; }
        public long AddressId { get; set; }
        public int PostSttId { get; set; }
        public string ApprovalLoginname { get; set; }
        public string ApprovalUsername { get; set; }
        public Nullable<long> ApprovalTime { get; set; }
        public string ApprovalNote { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Project Project { get; set; }
    }
}
