//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCS.LibraryMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageViResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageViResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCS.LibraryMessage.MessageViResource", typeof(MessageViResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đang bị khóa.
        /// </summary>
        internal static string Common__DuLieuDangBiKhoa {
            get {
                return ResourceManager.GetString("Common__DuLieuDangBiKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đang được mở khóa.
        /// </summary>
        internal static string Common__DuLieuDangMoKhoa {
            get {
                return ResourceManager.GetString("Common__DuLieuDangMoKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận vận hành chưa khai báo cấu hình hệ thống.
        /// </summary>
        internal static string Common__LoiCauHinhHeThong {
            get {
                return ResourceManager.GetString("Common__LoiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu có mã đã tồn tại trên hệ thống.
        /// </summary>
        internal static string Common__MaDaTonTaiTrenHeThong {
            get {
                return ResourceManager.GetString("Common__MaDaTonTaiTrenHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu thiếu trường thông tin bắt buộc.
        /// </summary>
        internal static string Common__ThieuThongTinBatBuoc {
            get {
                return ResourceManager.GetString("Common__ThieuThongTinBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thực hiện chức năng này.
        /// </summary>
        internal static string PcsEmployee__BanKhongCoQuyenThucHienChucNangNay {
            get {
                return ResourceManager.GetString("PcsEmployee__BanKhongCoQuyenThucHienChucNangNay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được sửa/xóa bài đăng khi đang ở tráng thái từ chối duyệt, chưa duyệt.
        /// </summary>
        internal static string PcsPost__ChiDuocSuaXoaBaiDangKhiOTrangThai {
            get {
                return ResourceManager.GetString("PcsPost__ChiDuocSuaXoaBaiDangKhiOTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án chưa có bài đăng nào chưa duyệt.
        /// </summary>
        internal static string PcsPost__DuAnChuaCoBaiDangNaoChuaDuyet {
            get {
                return ResourceManager.GetString("PcsPost__DuAnChuaCoBaiDangNaoChuaDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án không có bài đăng nào hợp lệ.
        /// </summary>
        internal static string PcsPost__DuAnKhongCoBaiDangNaoHopLe {
            get {
                return ResourceManager.GetString("PcsPost__DuAnKhongCoBaiDangNaoHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu thông tin lý do từ chối duyệt.
        /// </summary>
        internal static string PcsPost__ThieuThongTinLyDoTuChoiDuyet {
            get {
                return ResourceManager.GetString("PcsPost__ThieuThongTinLyDoTuChoiDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại bài đăng không thuộc dự án.
        /// </summary>
        internal static string PcsPost__TonTaiBaiDangKhongThuocDuAn {
            get {
                return ResourceManager.GetString("PcsPost__TonTaiBaiDangKhongThuocDuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái bài đăng không hợp lệ.
        /// </summary>
        internal static string PcsPost__TrangThaiBaiDangKhongHopLe {
            get {
                return ResourceManager.GetString("PcsPost__TrangThaiBaiDangKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án: {0} đã kết thúc.
        /// </summary>
        internal static string PcsProject__DuAnDaKetThuc {
            get {
                return ResourceManager.GetString("PcsProject__DuAnDaKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại dữ liệu bài đăng.
        /// </summary>
        internal static string PcsProject__TonTaiDuLieuBaiDang {
            get {
                return ResourceManager.GetString("PcsProject__TonTaiDuLieuBaiDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại dữ liệu địa chỉ.
        /// </summary>
        internal static string PcsProject__TonTaiDuLieuDiaChi {
            get {
                return ResourceManager.GetString("PcsProject__TonTaiDuLieuDiaChi", resourceCulture);
            }
        }
    }
}
