//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAS.LibraryBug {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AAS.LibraryBug.CodeResource", typeof(CodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS009.
        /// </summary>
        internal static string AasApplication_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasApplication_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS008.
        /// </summary>
        internal static string AasApplication_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasApplication_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS005.
        /// </summary>
        internal static string AasApplicationRole_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasApplicationRole_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS004.
        /// </summary>
        internal static string AasApplicationRole_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasApplicationRole_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS007.
        /// </summary>
        internal static string AasCredentialData_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasCredentialData_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS006.
        /// </summary>
        internal static string AasCredentialData_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasCredentialData_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS011.
        /// </summary>
        internal static string AasModule_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasModule_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS010.
        /// </summary>
        internal static string AasModule_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasModule_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS013.
        /// </summary>
        internal static string AasModuleRole_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasModuleRole_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS012.
        /// </summary>
        internal static string AasModuleRole_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasModuleRole_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS015.
        /// </summary>
        internal static string AasRole_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasRole_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS014.
        /// </summary>
        internal static string AasRole_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasRole_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS017.
        /// </summary>
        internal static string AasUser_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasUser_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS016.
        /// </summary>
        internal static string AasUser_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasUser_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS019.
        /// </summary>
        internal static string AasUserRole_CapNhatThatBai {
            get {
                return ResourceManager.GetString("AasUserRole_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS018.
        /// </summary>
        internal static string AasUserRole_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("AasUserRole_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS001.
        /// </summary>
        internal static string Common__KXDDDuLieuCanXuLy {
            get {
                return ResourceManager.GetString("Common__KXDDDuLieuCanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS003.
        /// </summary>
        internal static string Common__LoiCauHinhHeThong {
            get {
                return ResourceManager.GetString("Common__LoiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS002.
        /// </summary>
        internal static string Common__ThieuThongTinBatBuoc {
            get {
                return ResourceManager.GetString("Common__ThieuThongTinBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS020.
        /// </summary>
        internal static string Common_DuLieuDauVaoKhongChinhXac {
            get {
                return ResourceManager.GetString("Common_DuLieuDauVaoKhongChinhXac", resourceCulture);
            }
        }
    }
}
