//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleRole
    {
        public long Id { get; set; }
        public Nullable<long> CreateTime { get; set; }
        public Nullable<long> ModifyTime { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public Nullable<short> IsActive { get; set; }
        public long ModuleId { get; set; }
        public long RoleId { get; set; }
        public Nullable<short> IsAllowCreate { get; set; }
        public Nullable<short> IsAllowUpdate { get; set; }
        public Nullable<short> IsAllowDelete { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
    }
}
