//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCS.LibraryBug {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCS.LibraryBug.CodeResource", typeof(CodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS004.
        /// </summary>
        internal static string Common__DuLieuDauVaoKhongChinhXac {
            get {
                return ResourceManager.GetString("Common__DuLieuDauVaoKhongChinhXac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS001.
        /// </summary>
        internal static string Common__KXDDDuLieuCanXuLy {
            get {
                return ResourceManager.GetString("Common__KXDDDuLieuCanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS003.
        /// </summary>
        internal static string Common__LoiCauHinhHeThong {
            get {
                return ResourceManager.GetString("Common__LoiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS002.
        /// </summary>
        internal static string Common__ThieuThongTinBatBuoc {
            get {
                return ResourceManager.GetString("Common__ThieuThongTinBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS006.
        /// </summary>
        internal static string PcsAddress_CapNhatThatBai {
            get {
                return ResourceManager.GetString("PcsAddress_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS005.
        /// </summary>
        internal static string PcsAddress_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("PcsAddress_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS008.
        /// </summary>
        internal static string PcsEmployee_CapNhatThatBai {
            get {
                return ResourceManager.GetString("PcsEmployee_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS007.
        /// </summary>
        internal static string PcsEmployee_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("PcsEmployee_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS010.
        /// </summary>
        internal static string PcsPost_CapNhatThatBai {
            get {
                return ResourceManager.GetString("PcsPost_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS009.
        /// </summary>
        internal static string PcsPost_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("PcsPost_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS012.
        /// </summary>
        internal static string PcsProject_CapNhatThatBai {
            get {
                return ResourceManager.GetString("PcsProject_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS011.
        /// </summary>
        internal static string PcsProject_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("PcsProject_ThemMoiThatBai", resourceCulture);
            }
        }
    }
}
